version: '3.8'

services:
  data-service:
    build:
      context: .
      dockerfile: services/data/Dockerfile
    restart: always

  web-main:
    build:
      context: .
      dockerfile: packages/web-main/Dockerfile
    restart: always

  nginx:
    image: nginx:latest
