FROM node:16-alpine as deps
WORKDIR /app

COPY ./.yarn ./.yarn
COPY package.json yarn.lock .yarnrc.yml ./
COPY ./services/data/package.json ./services/data/package.json

RUN yarn install

FROM node:16-alpine as runner
WORKDIR /app

COPY --from=deps /app .
COPY ./services/data ./services/

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:/app/services/data/node_modules/.bin:$PATH

ENV NODE_ENV development
ENV PORT 3000
EXPOSE $PORT

WORKDIR /app/services/data
CMD ["yarn", "dev"]