name: 'Deploy Data Service'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Lint
        working-directory: services/data
        run: yarn lint

      - name: Test
        working-directory: services/data
        run: yarn test

  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_DATA_SERVICE }}
          IMAGE_TAG: latest # ${{ steps.vars.outputs.tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f services/data/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Update ECS
        # todo: move arguments to GH secrets
        run: aws ecs update-service --cluster funwithflights --service funwithflights-data-service --force-new-deployment

# todo uncomment for versioned images and task definitions
#      - name: Download task definition
#        # todo: move arguments to GH secrets
#        run: |
#          aws ecs describe-task-definition --task-definition funwithflights-data-service \
#          --query taskDefinition > task-definition.json
#
#      - name: Fill in the new image ID in the Amazon ECS task definition
#        id: task-def
#        uses: aws-actions/amazon-ecs-render-task-definition@v1
#        with:
#          task-definition: task-definition.json
#          # todo: move arguments to GH secrets
#          container-name: funwithflights-data-service
#          image: ${{ steps.build-image.outputs.image }}
#
#      - name: Deploy Amazon ECS task definition
#        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
#        with:
#          task-definition: ${{ steps.task-def.outputs.task-definition }}
#          # todo: move arguments to GH secrets
#          service: funwithflights-data-service
#          cluster: funwithflights
#          wait-for-service-stability: true
