name: 'Deploy web-main'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        id: build
        working-directory: packages/web-main
        run: yarn export

      - name: S3 copy
        id: s3-copy
        working-directory: packages/web-main
        run: aws s3 cp out s3://s3-web-main --recursive